### ISSUE TITLE
Compatible with gatling 3.4.?

### ISSUE THREAD

**Issue by ehmkah** [TinkoffCreditSystems/gatling-amqp-plugin#10]
I want to load-test our system which is connected via RabbitMQ.Therefore I try this plugin and I am asking myself is this plugin comatible to gatling 3.4.0 or should I use an old version of gatling? If its not compatible are there any plans to make it compatible again?

I get the following exeption if I try this plugin with gatling 3.4.0

`java.lang.NoSuchMethodError: io.gatling.core.CoreComponents.throttler()Lio/gatling/core/controller/throttle/Throttler;`

Warning: I am neither a scala nor gatling expert.

**Comment by ehmkah** [comment]
OK - plugin is not working with gatling 3.4. :-) I made two PRs for
- upgrade to gatling 3.3 https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/pull/12
- upgrade to gatling 3.4 https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/pull/13

@red-bashmak , @rene-ffs : Are you still maintaining this plugin?

**Comment by ehmkah** [comment]
has been fixed on the master.
